### PR TITLE
Chinese translation

### PR DESCRIPTION
**Pull request by shiki-tm**
i couldnt find the image files, if i need those please let me know where i can find them from the game folder. this is the script for simplified chinese but i would also like to add the traditional script later, is it okay to leave the translation id as just 2 letters "zh"? display name and locale are different of course. thank you

image

### CODE REVIEW

**Comment by requinDr** [comment]
Your PR looks good overall, but here are a few comments:
- name the folder and script with latin, non accentuated characters so we don't run into issues
- add [game.json](https://github.com/requinDr/tsukiweb-public/blob/main/public/static/en-mm/game.json). It contains the translated scenes titles (found in `arc.nsa` -> `image/title`)
- add [lang.json](https://github.com/requinDr/tsukiweb-public/blob/main/public/static/en-mm/lang.json). It contains a description of the translation, credits and UI translation. If you are unable to translate the UI that's fine, just leave it as is

For the image, usually we only extract `/tachi/osiete.jpg` (in arc.nsa) for each language. Since it requires masking work, upscaling and conversion, you can just drop it here in the conversation and I'll do it. You can chose to not include it, that would be fine too.

For the traditional script you can add it later as a different translation, no problem

**Comment by requinDr** [comment]
Also if the translation group still exists and is still active, please ask for their approval!

**Comment by shiki-tm** [comment]
thanks, the original group is supposedly not active anymore and cant get in contact with them. 
[tachi.zip](https://github.com/user-attachments/files/16054214/tachi.zip)

**Comment by shiki-tm** [comment]
"add [game.json](https://github.com/requinDr/tsukiweb-public/blob/main/public/static/en-mm/game.json). It contains the translated scenes titles (scenes titles of the translation are found in arc.nsa -> image/title)"
but i dont find those files. or are they just these image files?

image

**Comment by shiki-tm** [comment]
like a prologue,  murder impulse II, etc are scene titles right? theyre definitely in the game

**Comment by shiki-tm** [comment]
ok found it but theyre all jpgs. am i supposed to merge them somehow into a json file?

**Comment by requinDr** [comment]
You are supposed to write them manually, one by one into the json file. I'm afraid there's no better way, sorry. I did that for 2 languages and @loicfrance did 2 others too.
Quite the borring task, but necessary to achieve responsiveness, good quality and futur improvements

**Comment by shiki-tm** [comment]
oh i see, i didnt know sorry! thats no problem, but its late here so ill work on this tomorrow again. thanks a lot for your help. actually they decided to leave the english names for only arcueid and ciel even though they have chinese sounding name equivalents, id like to change that in the script and other parts so that its consistent so ill edit that script too

**Comment by requinDr** [comment]
I have no problem with that, make the changes you believe are for the best. Thank you for your work!

**Comment by shiki-tm** [comment]
ill do the traditional script tomorrow

**Comment by requinDr** [comment]
See https://github.com/requinDr/tsukiweb-public/commit/b4278956b2139bd68391f2d0c68300ca5a2d62a2 for what I've changed for your PR.
- Multiple links for the translation team aren't supported (maybe later).
- Local should be `zh-CN` instead of `zh_CN`
- I used notepad++ to convert the fullscript to utf-8

Overall you did a good job  

You can see the result of your work here https://tsukidev.holofield.fr/title  
The menus are working and you can see that the font looks fine. We use the font "Ubuntu" that works for pretty much all of utf-8 afaik.  
At the moment I still have an issue on playing the scene, but hopefully it will soon be fixed

**Pull request merged**
