### PR TITLE
Significant improvements for the UI translation of both chinese scripts

### PR DESCRIPTION
**Pull request by shiki-tm**
There were some errors and now its much more simpler and easier to understand the menus and buttons. also translated basically all the english to chinese now. with this it should be done. thank you for everything

### CODE REVIEW

**Comment by requinDr** [comment]
Thanks for the improvements, they're much appreciated.
I left two things to fix or it won't work. Once it's fixed I'll merge your PR

**Comment by requinDr** [comment]
I thought you would fix them since I described what the issues were and it was your work.
I guess I'll do it

**Comment by shiki-tm** [comment]
?? I'm sorry I didn't understand that. 
Where are the issues described ? 
I can fix them no problem

**Comment by requinDr** [comment]
I thought my review was visible before but it was not, sorry!
Now it should be visible above

**Comment by shiki-tm** [comment]
ok got it. sorry for the trouble. added the small fixes

**Pull request merged**
